[package]
name = "faster-pest-generator"
version = "0.2.0-alpha.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest_meta = "2.7"
