[package]
name = "faster-pest"
authors = ["Mubelotix <mubelotix@gmail>"]
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.5"
faster-pest-derive = { path="../faster-pest-derive" }

[dev-dependencies]
pest_derive = "2.5"
